### ISSUE TITLE
Documenter les outils recommandés pour un travail sur les profils "en local"

### ISSUE THREAD

**Issue by thbar** [etalab/transport-profil-netex-fr#66]
Comme discuté au GT7, @Henault va travailler directement sur un nouveau profil ici et en markdown, et on a une session prévue ce mercredi pour mettre en place les outils pour qu'il puisse travaille en local sur son ordinateur.

J'en profite pour documenter ce que je vais lui proposer (qui sont des outils assez standards).

### GitHub Desktop

Si on est sur Mac ou sur Windows (mais pas sous Linux), GitHub propose une application gratuite qui est assez confortable à utiliser (davantage que la ligne de commande aka CLI pour un non développeur).

Elle est disponible ici: https://desktop.github.com

Je détaillerai ici comment s'en servir en quelques lignes.

### Visual Studio Code

Disponible sur toutes les plateformes gratuitement, Visual Studio Code permet d'éditer de nombreux formats et dispose de quantités d'extensions pratiques (dont certaines pour faciliter le travail avec le Markdown qui est utilisé pour les profils à présent).

Application disponible ici : https://code.visualstudio.com/

### Workflow recommandé

1. Vérifier qu'on a un compte GitHub
2. Activer le 2FA (authentification à deux facteurs) dessus
3. Se faire ajouter aux "équipes" qui peuvent travailler sur le repository du profil concerné (voir via moi ou @TuThoThai typiquement)
4. Installer GitHub Desktop et VSCode (voir plus haut)
5. "Cloner" le repository (explications à fournir)
6. Créer une branche de travail avec un nom descriptif (généralement en minuscules et avec des tirets, pas d'espaces etc)
7. Faire des "commits" régulièrement dessus pour sauvegarder les travaux
8. Ne pas hésiter à créer une "Pull Request" dès que possible pour favoriser la discussion sur les travaux
9. Ne pas hésiter à créer des TODOS avec la syntaxe `- [ ] XYZ` dans la description pour ne rien oublier
10. Review en cours de route ou à la fin
11. Merge et intégration dans `main`/`master` (ce qui ne publie pas une nouvelle version, et modifie uniquement la version "en cours")

Voir https://docs.github.com/en/get-started/using-github/github-flow

### TODOs

- [ ] Préciser d'éviter les CSS customs (voir profil SIRI FR)
- [ ] Documenter comment faire une preview simple (locale), intermédiaire (sur GitHub web) ou plus fidèle (avec le rendu de production visible sur https://normes.transport.data.gouv.fr)
- [ ] Ne pas hésiter à documenter les questions de @Henault en première approche, ça resservira

**Comment by Henault** [comment]
Suite à première session de mise en place des outils reste avec @thbar à clarifier :

- le preview MD
- l'insertion de tableaux

**Comment by TuThoThai** [comment]
Ce qui a été validé en plénière GT7 en date du 21 novembre 2024 : lancement de cette mini-documentation liée aux outils et à l'usage de GitHub.
Contributeurs identifiés : 
- @thbar 
- @prhod
- @ptitfred 
- @TuThoThai
